// apps/angular-app/src/app/counter-page/counter-page.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-counter-page',
  templateUrl: './counter-page.component.html',
  styleUrls: ['./counter-page.component.css'],
})
export class CounterPageComponent {}

<h1>Counter</h1>

<app-counter [value]="counter"></app-counter>
<app-counter [value]="doubled"></app-counter>
<button (click)="increment()">Increment</button>

// apps/react-app/src/counter/CounterPage.tsx
import { useCallback, useMemo, useState } from "react";
import { useTitle } from "../useTitle";
import Counter from "./Counter";
import styles from "./CounterPage.module.css";

function CounterPage() {
  const [counter, setCounter] = useState(0);
  const doubled = useMemo(() => counter * 2, [counter]);
  const increment = useCallback(() => setCounter((current) => current + 1), []);

  useTitle("Counter | React app");

  return (
    <>
      <h1 className={styles.h1}>Counter</h1>
      <Counter value={counter} />
      <Counter value={doubled} />
      <button onClick={increment}>Increment</button>
    </>
  );
}

export default CounterPage;
